services:
  openclaw:
    image: lqepoch/openclaw:latest
    container_name: openclaw-data-openai-1
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - openclaw-data-openai-1:/home/node/.openclaw
    ports:
      - "18789:18789"

volumes:
  openclaw-data-openai-1:
    name: openclaw-data-openai-1
